### ISSUE TITLE
Clear face but not accurate

### ISSUE THREAD

**Issue by GunnyNinja** [Gourieff/sd-webui-roop-nsfw#20]
I started with https://github.com/IntellectzProductions/sd-webui-faceswap.git which is pretty accurate to the uploaded photo, but the face is blurry. The GE version is not blurry but does not look like the uploaded face. I wish you guys could combine your efforts to give the accuracy and clear face at the same time.

**Comment by Gourieff** [comment]
https://github.com/IntellectzProductions/sd-webui-faceswap.git - is literally a very simplified version of the original "sd-webui-roop" 
The face is accurate there only because of no enhancers are in use after the face swap is done
And this is the reason why the face is blurry
"inswapper_128.onnx" model has low resolution and that's why the result needs to be enhanced with CodeFormer or GFPGAN
The enhancement makes a final face slightly different from an original one, the closer a face in a picture - the more likely that it may differ in some details
You can try to set "Restore Face" option to "None" in Roop-GE and I'm sure the result will be about the same as via sd-webui-faceswap

**Comment by GunnyNinja** [comment]
What you guys do is amazing. I wish I understood it all better. I did some tests and, as you say, without restore face, the results are pixelated, but not blurry. There is no difference in accuracy. It's not quite the same as the other model in either resolution or accuracy. I tried each upscaler and some are a bit TOO sharp, to the point of being unrealistic. I prefer Lanczos. Best combination of clarity and realism. Obviously a clear face is the goal, but what would it take to get it to look more like the source image?
