### ISSUE TITLE
GPU: No performance benefit?

### ISSUE THREAD

**Issue by adde88** [Gourieff/sd-webui-roop-nsfw#28]
https://github.com/Gourieff/sd-webui-roop-nsfw/blame/c663408f4baf01932657e7a502a732bffeb31ac9/scripts/swapper.py#L19

This is regarding that line above.
According to: e6333fbe5a0f3e6a515852388151f1db2315c45d , using GPU has no performance benefits compared to using the CPU.
Wouldn't this also save resources needed by the GPU, like VRAM etc? 🤔 

Just thought i'd ask. :)

**Comment by Gourieff** [comment]
Roop-GE also uses CPU execution provider only
I tried to rework the code to use GPU, but this's really no performance benefit, even it causes performance drop (too long loading of GPU execution providers, VRAM usage and inability to use "deepcopy" method for an already loaded insightface analysis model)
Considering that the standard Onnxruntime (neither GPU nor Silicon version) package is installed, it has only one execution provider available (CPUExecutionProvider), so that lines `providers = onnxruntime.get_available_providers()` and `providers = ["CPUExecutionProvider"]` are totally equal
`onnxruntime.get_available_providers()` returns `["CPUExecutionProvider"]`
But I think this is more correct way to init execution provider, rather than set this value manually
Roop-GE works faster than the original Roop extension due to the fact that the original Author forgot to return the previous method of loading an insightface analysis model
I returned it in this commit https://github.com/Gourieff/sd-webui-roop-nsfw/commit/899db45f997f53a12129ba29624acca38f2919c5
