### ISSUE TITLE
Linux install instructions?

### ISSUE THREAD

**Issue by tensiondriven** [Gourieff/sd-webui-roop-nsfw#4]
Hello - Thanks for making this available!

Is Roop compatible with automatic1111 when run on linux (docker)?

If so, it would be great to have notes in the readme for how to install.
if not, it would also be great to have that mentioned in the readme!

**Comment by Gourieff** [comment]
Hello there!
Yes, you can try to install it as any other extension inside the "Extensions" tab of sd-webui
If you encounter any issues with building dependencies, try to install them manually one-by-one
But I think in Linux it should be much smoother than in Windows (due to the lack of C++ Build Tools from the box)
Feel free to write about the result - and I will add a line in the Readme
